### data configs

data: 'fss1k'
data_path: 'data/fss-1000'

dim_x: 3 # input dimension
num_workers: 4

ways: 1
shots: 5
base_size: 224
crop_size: [192, 192]


### training configs

n_steps: 100000 # total training steps
global_batch_size: 4 # number of datasets (multi-task functions) in a batch

lr: 0.00025 # learning rate
lr_schedule: 'poly'
lr_warmup: 1000


### logging configs

log_iter: 100 # interval between tqdm and tensorboard logging of training metrics
val_iter: 1000 # interval between validation and tensorboard logging of validation metrics
save_iter: 1000 # interval between checkpointing
log_dir: 'runs_fss1k' # directory for saving checkpoints and logs