### data configs

data: 'template'
data_path: 'data/template/path_for_the_stored_data'
tasks: ['task_1', 'task_2', 'task_3'] # list of task names
task_blocks: [['task_1'], ['task_2', 'task_3']] # list of blocks or groups of tasks to be considered as a single task by concatenations

dim_x: 1 # input dimension
dim_ys: {'task_1': 1, 'task_2': 1, 'task_3': 1} # output dimensions or channels

split_ratio: [0.8, 0.1, 0.1]
num_workers: 4

colors: {'task_1': 'r', 'task_2': 'g', 'task_3': 'b'}

dim_x: 1 # input dimension
dim_ys: {'task_1': 1, 'task_2': 2} # output dimensions or channels

split_ratio: [0.8, 0.1, 0.1]
num_workers: 4

### test configs

ts_test: 200
ns_G: 5 # number of global sampling (for JTP, MTP)
ns_T: 5 # number of per-task samplings (for STP, MTP)

imputer_path: 'experiments/runs_template/stp/checkpoints/best_nll.pth' # imputer checkpoint path (for JTP)

### checkpointing configs

eval_dir: 'runs_template' # directory where the models to evaluate are stored