# data configs
data: 'synthetic_tasknoised'
data_path: 'data/multi_data_tasknoised.pth'
tasks: ['sine', 'tanh', 'sigmoid', 'gaussian']
eval_dir: 'runs_synthetic_tasknoised'

# evaluation configs
global_batch_size: 10
M: 10
N: 1000
K: 5
L: 5